### ISSUE TITLE
How to use the WebNN backend?

### ISSUE THREAD

**Issue by a-sully** [webatintel/ort-toolkit#1]
This repo is an awesome resource - thanks for putting it together!

The readme suggests that it's possible to run models with a WebNN backend. However, WebNN support isn't built into ORT Web by default and doesn't seem to be in included in any of the versions I've tried from [the CDN](https://cdn.jsdelivr.net/npm/onnxruntime-web@latest/)

Questions:

1. Do you know if any of the builds from the CDN have WebNN support enabled by default?
2. If not, would it be possible to add a WebNN-enabled build to https://github.com/webatintel/ort-web?
3. If not, any other suggestions?

Thanks!

**Comment by gyagp** [comment]
Sorry that I didn't turn on the notification so I totally missed this issue until my team member told me about this today. 
I'm not sure if WebNN has been built together with https://www.jsdelivr.com/package/npm/onnxruntime-web. However, it's not functional today due to lack of newer emsdk support (at least 3.1.47 and a draft upgrade PR by MS can be found at https://github.com/microsoft/onnxruntime/pull/18709). The current blocking issue to upgrade emsdk in ORT is we have big perf regression for wasm backend. 
Anyway, you may still build it from source code by manually incorporating emsdk PR, and I have a script for build at https://github.com/webatintel/toolkit/blob/master/misc/ort.py. 
If you really have trouble to build it by yourself, I may try to put a local build at https://github.com/webatintel/ort-web. But I may not have bandwidth to release frequently.

**Comment by qwu16** [comment]
@a-sully WebNN has been built into dev ort web, you can refer to 1.18.0-dev.20240130-9f68a27c7a in https://www.npmjs.com/package/onnxruntime-web?activeTab=versions.

**Comment by a-sully** [comment]
Amazing, thanks! :D
